apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-<workspacename>
  namespace: <namespacename>
    
spec:
      commands:
        - apply:
            component: che-code-injector
          id: init-container-command
        - exec:
            commandLine: >-
              nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
              2>&1 &
            component: che-code-runtime-description
          id: init-che-code-command
      components:
        - attributes:
            app.kubernetes.io/component: che-code-runtime
            app.kubernetes.io/part-of: che-code.eclipse.org
            controller.devfile.io/container-contribution: true
          container:
            cpuRequest: 30m
            env: #Get the env var values from your cluster
                - name: CHE_DASHBOARD_URL
                  value: https://devspaces.rh-squad-7f0bc321fea8726bc360106c441721a7-0000.eu-gb.containers.appdomain.cloud
                - name: CHE_PLUGIN_REGISTRY_URL
                  value:  https://devspaces.rh-squad-7f0bc321fea8726bc360106c441721a7-0000.eu-gb.containers.appdomain.cloud/plugin-registry/v3
                - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                  value: 'http://plugin-registry.openshift-operators.svc:8080/v3'
                - name: CLUSTER_CONSOLE_URL
                  value: https://console-openshift-console.rh-squad-7f0bc321fea8726bc360106c441721a7-0000.eu-gb.containers.appdomain.cloud
                - name: CLUSTER_CONSOLE_TITLE
                  value: OpenShift console
                - name: OPENVSX_REGISTRY_URL
                  value: ''
            memoryRequest: 256Mi
            sourceMapping: /projects
            cpuLimit: 500m
            volumeMounts:
              - name: checode
                path: /checode
            memoryLimit: 1024Mi
            #Get the image values from pre-existing DevWorkSpaceTemplate by creating Dev Space workspace manually
            image: registry.redhat.io/devspaces/udi-rhel8@sha256:571ceed7b4b886b7f989ba193fa74ec863600f56f7c0045f3a1af6dadf09f85b
            endpoints:
              - attributes:
                  cookiesAuthEnabled: true
                  discoverable: false
                  type: main
                  urlRewriteSupported: true
                exposure: public
                name: che-code
                protocol: https
                secure: false
                targetPort: 3100
              - attributes:
                  discoverable: false
                  urlRewriteSupported: false
                exposure: public
                name: code-redirect-1
                protocol: http
                targetPort: 13131
              - attributes:
                  discoverable: false
                  urlRewriteSupported: false
                exposure: public
                name: code-redirect-2
                protocol: http
                targetPort: 13132
              - attributes:
                  discoverable: false
                  urlRewriteSupported: false
                exposure: public
                name: code-redirect-3
                protocol: http
                targetPort: 13133
          name: che-code-runtime-description
        - name: checode
          volume: {}
        - container:
            cpuRequest: 30m
            command:
              - /entrypoint-init-container.sh
            env: #Get the env var values from your cluster
                 - name: CHE_DASHBOARD_URL
                   value: https://devspaces.rh-squad-7f0bc321fea8726bc360106c441721a7-0000.eu-gb.containers.appdomain.cloud
                 - name: CHE_PLUGIN_REGISTRY_URL
                   value: https://devspaces.rh-squad-7f0bc321fea8726bc360106c441721a7-0000.eu-gb.containers.appdomain.cloud/plugin-registry/v3
                 - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                   value: 'http://plugin-registry.openshift-operators.svc:8080/v3'
                 - name: CLUSTER_CONSOLE_URL
                   value: https://console-openshift-console.rh-squad-7f0bc321fea8726bc360106c441721a7-0000.eu-gb.containers.appdomain.cloud
                 - name: CLUSTER_CONSOLE_TITLE
                   value: OpenShift console
                 - name: OPENVSX_REGISTRY_URL
                   value: ''
            memoryRequest: 32Mi
            sourceMapping: /projects
            cpuLimit: 500m
            volumeMounts:
              - name: checode
                path: /checode
            memoryLimit: 256Mi
            #Get the image values from pre-existing DevWorkSpaceTemplate by creating Dev Space workspace manually
            image: registry.redhat.io/devspaces/code-rhel8@sha256:d4c7e8065d1903dd925a1c8a538b8fb88961eb58b077cd206a1c743916bc1ffb
          name: che-code-injector
      events:
        postStart:
          - init-che-code-command
        preStart:
          - init-container-command
parameters:
- description: Username
  name: USERNAME              
